name: Sync code

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  check:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Determine branch
        run: |
          openwrt_branch="${GITHUB_REF#refs/heads/}"
          echo ${openwrt_branch}