name: Sync code

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  check:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Determine branch
        run: |
          openwrt_branch="${GITHUB_REF#refs/heads/}"
          echo ${openwrt_branch}
          bash main.sh update

      - name: Determine changes
        run: |
          [[ ! -z $(git status -s) ]] && git pull && git add . && git commit -m "CI: sync code" && git push